services:
  - type: web
    name: textutils-web
    env: python
    region: frankfurt  # Better for India
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn TextUtils.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: TextUtils.settings
      - key: PYTHON_VERSION
        value: 3.12.1